name: Docker Image CI

on:
  push:
    branches: [ wth/github-actions ]
  # pull_request:
  #   branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - run: docker ps -a
      - run: ls -l
